Importing Necessary Libraries

In [137]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

Importing Dataset

In [138]:
confirmed_df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/refs/heads/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
confirmed_df.head(2)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,209322,209340,209358,209362,209369,209390,209406,209436,209451,209451
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,334391,334408,334408,334427,334427,334427,334427,334427,334443,334457

In [139]:
recovery_df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/refs/heads/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')
recovery_df.head(2)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [140]:
death_df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/refs/heads/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
death_df.head(2)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7896,7896,7896,7896,7896,7896,7896,7896,7896,7896
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3598,3598,3598,3598,3598,3598,3598,3598,3598,3598

In [141]:
DATA_PATH = os.path.join(os.path.dirname(os.getcwd()),'COVID-19-ANALYSIS','API_SP.POP.TOTL_DS2_en_csv_v2_115541.csv')

In [142]:
total_population_2025 = pd.read_csv(DATA_PATH, skiprows=4)
total_population_2025.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,...,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN,NaN

Checking Datatypes and rows/columns

In [143]:
datasets = {'confirmed_df':confirmed_df,'recovery_df':recovery_df,'death_df':death_df,'total_population_2025':total_population_2025}

In [144]:
for name, df in datasets.items():
    print(f"Checking {name}...")
    
    # Null check
    print(f"Nulls: {df.isnull().sum().sum()}")
    
    # Shape
    print(f"Shape: {df.shape}\n")

Checking confirmed_df...
Nulls: 202
Shape: (289, 1147)

Checking recovery_df...
Nulls: 201
Shape: (274, 1147)

Checking death_df...
Nulls: 202
Shape: (289, 1147)

Checking total_population_2025...
Nulls: 627
Shape: (266, 71)

In [145]:
for name,df in datasets.items():
    print(f"{name}...")
    print(df.info())
    print(df.columns,'\n')

confirmed_df...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Columns: 1147 entries, Province/State to 3/9/23
dtypes: float64(2), int64(1143), object(2)
memory usage: 2.5+ MB
None
Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '2/28/23', '3/1/23', '3/2/23', '3/3/23', '3/4/23', '3/5/23', '3/6/23',
       '3/7/23', '3/8/23', '3/9/23'],
      dtype='object', length=1147)

recovery_df...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Columns: 1147 entries, Province/State to 3/9/23
dtypes: float64(2), int64(1143), object(2)
memory usage: 2.4+ MB
None
Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '2/28/23', '3/1/23', '3/2/23', '3/3/23', '3/4/23', '3/5/23', '3/6/23',
       '3/7/23', '3/8/23', '3/9/23'],
      dtype='object', length=1147)

death_df...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Columns: 1147 entries, Province/State to 3/9/23
dtypes: float64(2), int64(1143), object(2)
memory usage: 2.5+ MB
None
Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '2/28/23', '3/1/23', '3/2/23', '3/3/23', '3/4/23', '3/5/23', '3/6/23',
       '3/7/23', '3/8/23', '3/9/23'],
      dtype='object', length=1147)

total_population_2025...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            264 non-null    float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            264 non-null    float64
 8   1964            264 non-null    float64
 9   1965            264 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            265 non-null    float64
 35  1991            265 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            265 non-null    float64
 67  2023            265 non-null    float64
 68  2024            265 non-null    float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.7+ KB
None
Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='object')

Creating different copy for analysis and cleaning

In [146]:
working_datasets = {}

for name, dataset in datasets.items():
    working_datasets[f"working_{name}"] = dataset.copy()
working_datasets.keys()

dict_keys(['working_confirmed_df', 'working_recovery_df', 'working_death_df', 'working_total_population_2025'])

## Data Cleaning
### Finding Unique Values

In [147]:
working_datasets["working_confirmed_df"]['Province/State'].unique()

array([nan, 'Australian Capital Territory', 'New South Wales',
       'Northern Territory', 'Queensland', 'South Australia', 'Tasmania',
       'Victoria', 'Western Australia', 'Alberta', 'British Columbia',
       'Diamond Princess', 'Grand Princess', 'Manitoba', 'New Brunswick',
       'Newfoundland and Labrador', 'Northwest Territories',
       'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island',
       'Quebec', 'Repatriated Travellers', 'Saskatchewan', 'Yukon',
       'Anhui', 'Beijing', 'Chongqing', 'Fujian', 'Gansu', 'Guangdong',
       'Guangxi', 'Guizhou', 'Hainan', 'Hebei', 'Heilongjiang', 'Henan',
       'Hong Kong', 'Hubei', 'Hunan', 'Inner Mongolia', 'Jiangsu',
       'Jiangxi', 'Jilin', 'Liaoning', 'Macau', 'Ningxia', 'Qinghai',
       'Shaanxi', 'Shandong', 'Shanghai', 'Shanxi', 'Sichuan', 'Tianjin',
       'Tibet', 'Unknown', 'Xinjiang', 'Yunnan', 'Zhejiang',
       'Faroe Islands', 'Greenland', 'French Guiana', 'French Polynesia',
       'Guadeloupe', 'Martinique', 'Mayotte', 'New Caledonia', 'Reunion',
       'Saint Barthelemy', 'Saint Pierre and Miquelon', 'St Martin',
       'Wallis and Futuna', 'Aruba', 'Bonaire, Sint Eustatius and Saba',
       'Curacao', 'Sint Maarten', 'Cook Islands', 'Niue', 'Anguilla',
       'Bermuda', 'British Virgin Islands', 'Cayman Islands',
       'Channel Islands', 'Falkland Islands (Malvinas)', 'Gibraltar',
       'Guernsey', 'Isle of Man', 'Jersey', 'Montserrat',
       'Pitcairn Islands', 'Saint Helena, Ascension and Tristan da Cunha',
       'Turks and Caicos Islands'], dtype=object)

In [148]:
working_datasets["working_confirmed_df"]['Country/Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Diamond Princess', 'Djibouti', 'Dominica', 'Dominican Republic',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Korea, North', 'Korea, South', 'Kosovo', 'Kuwait', 'Kyrgyzstan',
       'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'MS Zaandam',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Summer Olympics 2020', 'Suriname',
       'Sweden', 'Switzerland', 'Syria', 'Taiwan*', 'Tajikistan',
       'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Tuvalu', 'US',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'West Bank and Gaza', 'Winter Olympics 2022', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [149]:
for name, df in working_datasets.items():

    if "population" in name:
        continue

    df["Province/State"] = df["Province/State"].fillna("Unknown")

    print(f"\n{name.upper()}")
    print(df.isnull().sum())

WORKING_CONFIRMED_DF
Province/State    0
Country/Region    0
Lat               2
Long              2
1/22/20           0
                 ..
3/5/23            0
3/6/23            0
3/7/23            0
3/8/23            0
3/9/23            0
Length: 1147, dtype: int64

WORKING_RECOVERY_DF
Province/State    0
Country/Region    0
Lat               1
Long              1
1/22/20           0
                 ..
3/5/23            0
3/6/23            0
3/7/23            0
3/8/23            0
3/9/23            0
Length: 1147, dtype: int64

WORKING_DEATH_DF
Province/State    0
Country/Region    0
Lat               2
Long              2
1/22/20           0
                 ..
3/5/23            0
3/6/23            0
3/7/23            0
3/8/23            0
3/9/23            0
Length: 1147, dtype: int64

In [150]:
for name, dataset in working_datasets.items():

    if 'population' in name:
        continue

    mask = dataset['Country/Region'].str.contains(r'[/*|\\]', na=False)
    print(f"\nBEFORE CLEANING → {name}")
    print(dataset.loc[mask, 'Country/Region'].unique())

    dataset['Country/Region'] = (
        dataset['Country/Region'].str.replace(r'[/*|\\]', ' ', regex=True).str.replace(r'\s+', ' ', regex=True).str.strip()
    )

    
    mask_after = dataset['Country/Region'].str.contains(r'[/*|\\]', na=False)
    print(f"AFTER CLEANING → {name}")
    print("Remaining issues:", mask_after.sum())

BEFORE CLEANING → working_confirmed_df
['Taiwan*']
AFTER CLEANING → working_confirmed_df
Remaining issues: 0

BEFORE CLEANING → working_recovery_df
['Taiwan*']
AFTER CLEANING → working_recovery_df
Remaining issues: 0

BEFORE CLEANING → working_death_df
['Taiwan*']
AFTER CLEANING → working_death_df
Remaining issues: 0

In [151]:
for name,df in working_datasets.items():
    if 'population' in name:
        continue
    print(name)
    print('Lat',df['Lat'].isnull().sum())
    print('Long',df['Long'].isnull().sum(),'\n')

working_confirmed_df
Lat 2
Long 2

working_recovery_df
Lat 1
Long 1

working_death_df
Lat 2
Long 2

In [152]:
for name, df in working_datasets.items():
    if 'pop' in name:
        continue

    print(f"\n{name.upper()}")

    mask = df['Lat'].isnull() | df['Long'].isnull()

    print(df.loc[mask, df.columns[:4]])

WORKING_CONFIRMED_DF
            Province/State Country/Region  Lat  Long
53  Repatriated Travellers         Canada  NaN   NaN
89                 Unknown          China  NaN   NaN

WORKING_RECOVERY_DF
   Province/State Country/Region  Lat  Long
74        Unknown          China  NaN   NaN

WORKING_DEATH_DF
            Province/State Country/Region  Lat  Long
53  Repatriated Travellers         Canada  NaN   NaN
89                 Unknown          China  NaN   NaN

In [153]:
working_datasets['working_confirmed_df'][working_datasets['working_confirmed_df']['Province/State'] == 'Repatriated Travellers']

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
53,Repatriated Travellers,Canada,NaN,NaN,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13

We found Canada Lat and Long -> 43.652961, -79.382633.

But for China as we don't have state we will be filling it with unkown.

In [160]:
lat = 43.652961
long = -79.382633

for name, df in working_datasets.items():
    if 'pop' in name:
        continue
    mask_rt = df['Province/State'] == 'Repatriated Travellers'
    df.loc[mask_rt, ['Lat', 'Long']] = [lat, long]

    mask_missing = df['Lat'].isnull() | df['Long'].isnull()

    print(f"\n{name} → Missing coords: {mask_missing.sum()}")
    print(df.loc[mask_missing, df.columns[:4]].head(3))

working_confirmed_df → Missing coords: 1
   Province/State Country/Region  Lat Long
89        Unknown          China  NaN  NaN

working_recovery_df → Missing coords: 1
   Province/State Country/Region  Lat Long
74        Unknown          China  NaN  NaN

working_death_df → Missing coords: 1
   Province/State Country/Region  Lat Long
89        Unknown          China  NaN  NaN

### Finding Duplicated Rows

Checking for only Country and State 'cause checking for all will make system compute more and we can still check duplicated countries and states.

In [ ]:
analysis_datasets = {}

for name, df in working_datasets.items():
    if 'pop' in name:
        continue

    melted = df.melt(
        id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'],
        var_name='Date',
        value_name='Cases'
    )

    melted['Date'] = pd.to_datetime(melted['Date'])

    analysis_datasets[f'analysis_{name[8:]}'] = melted

C:\Users\shubh\AppData\Local\Temp\ipykernel_10140\1644134645.py:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  melted['Date'] = pd.to_datetime(melted['Date'])
C:\Users\shubh\AppData\Local\Temp\ipykernel_10140\1644134645.py:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  melted['Date'] = pd.to_datetime(melted['Date'])
C:\Users\shubh\AppData\Local\Temp\ipykernel_10140\1644134645.py:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  melted['Date'] = pd.to_datetime(melted['Date'])

In [162]:
for name,df in analysis_datasets.items():
    print(name)
    print(df[df.duplicated()])

analysis_confirmed_df
Empty DataFrame
Columns: [Province/State, Country/Region, Lat, Long, Date, Cases]
Index: []
analysis_recovery_df
Empty DataFrame
Columns: [Province/State, Country/Region, Lat, Long, Date, Cases]
Index: []
analysis_death_df
Empty DataFrame
Columns: [Province/State, Country/Region, Lat, Long, Date, Cases]
Index: []

We dont have any duplicated rows.

## Analysis